//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public byte SiteID { get; set; }
        public string SiteDesc { get; set; }
    }
}
