using System.ComponentModel.DataAnnotations;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        [Required]        
        public long id { get; set; }

        [Display(Name = "Employee Name")]
        public string name { get; set; }
        public System.DateTime bdate { get; set; }
        public string place { get; set; }
    }
}
